#! /bin/sh

if [ -f $HOME/.config/bspwm/screenlayout.sh ];then /bin/sh $HOME/.config/bspwm/screenlayout.sh ;fi
if [ -f $HOME/.config/bspwm/host.sh ];then /bin/sh $HOME/.config/bspwm/host.sh;fi

pgrep sxhkd > /dev/null || sxhkd &
pgrep polybar >/dev/null || polybar -q main -c "$HOME/.config/polybar/config.ini"&

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

pgrep alacritty > /dev/null || alacritty &
pgrep picom > /dev/null || picom &
pgrep dunst >/dev/null || dunst &
numlockx on &
setxkbmap fr us&
nitrogen --restore &
pgrep activate-linux >/dev/null  || (sleep 2;activate-linux -d)&
