name: update the nix flake lock automatically every week
run-name: update
on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: get repo
        uses: actions/checkout@v4.2.2

      - name: install nix
        uses: https://github.com/cachix/install-nix-action@v31

      - name: run the update
        run: nix flake update
