name: Build iso when a new version is pushed
run-name: iso building
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get repo
        uses: actions/checkout@v4.2.2

      - name: install nix
        uses: https://github.com/cachix/install-nix-action@v31

      - name: install go
        uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>=1.20.1'

      #- name: build iso
      #  run: make iso

      - name: get commit tag
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: create tag
        run: |
          TAG=$(git rev-parse --short HEAD)
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag ${{steps.vars.outputs.TAG}}
          git push origin ${{steps.vars.outputs.TAG}}
      
      - name: create release
        uses: https://gitea.com/actions/release-action@main
        with:
          tag_name: ${{steps.vars.outputs.TAG}}
          files: |-
            flake.nix
          api_key: '${{secrets.RELEASE_TOKEN}}'
