name: Build iso when a new version is pushed
run-name: iso building
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get repo
        uses: actions/checkout@v4.2.2

      - name: install nix
        uses: https://github.com/cachix/install-nix-action@v31

      - name: install go
        uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>=1.20.1'

      #- name: build iso
      #  run: make iso
      
      - name: create release
        uses: https://gitea.com/actions/release-action@main
        with:
          files: |-
            flake.nix
          api_key: '${{secrets.RELEASE_TOKEN}}'
