#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5
bspc desktop 1 -f
pgrep -x polybar || polybar -q main -c "$HOME/.config/polybar/config-small.ini"&

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config focus_follows_pointer true
bspc config gapless_monocle      true

pgrep -x alacritty > /dev/null || alacritty &

#autostart appps
picom --experimental-backends &
nitrogen --restore &
dunst &
numlockx on &
setxkbmap fr us&
killall activate-linux
(sleep 1;activate-linux -c 1-1-1-0.7 -V 50 -H 70 -d)&
